### ISSUE TITLE
Ability to show progress

### ISSUE THREAD

**Issue by brycethornton** [shayonj/pg-osc#102]
I'm currently attempting to use `ps-osc` on a two billion row, 482 GB (223 table/259 index) table. Needless to say, it's taking a long time. I'm actually starting to doubt if it's actually working as the output is just this so far after twenty hours:

```
{"name":"pg-online-schema-change","hostname":"Bryces-MacBook-Pro-M2.local","pid":19905,"level":40,"time":"2023-07-27T17:34:49.736-04:00","v":0,"msg":"DEPRECATED: -w is deprecated. Please pass PGPASSWORD environment variable instead.","version":"0.9.2"}
WARNING:  there is already a transaction in progress
{"name":"pg-online-schema-change","hostname":"Bryces-MacBook-Pro-M2.local","pid":19905,"level":30,"time":"2023-07-27T17:34:51.126-04:00","v":0,"msg":"Setting up audit table","audit_table":"pgosc_at_mytable_c16c36","version":"0.9.2"}
{"name":"pg-online-schema-change","hostname":"Bryces-MacBook-Pro-M2.local","pid":19905,"level":30,"time":"2023-07-27T17:34:51.382-04:00","v":0,"msg":"Setting up triggers","version":"0.9.2"}
WARNING:  there is already a transaction in progress
WARNING:  there is already a transaction in progress
WARNING:  there is no transaction in progress
{"name":"pg-online-schema-change","hostname":"Bryces-MacBook-Pro-M2.local","pid":19905,"level":30,"time":"2023-07-27T17:34:51.714-04:00","v":0,"msg":"Setting up shadow table","shadow_table":"pgosc_st_mytable_c16c36","version":"0.9.2"}
WARNING:  there is already a transaction in progress
WARNING:  there is already a transaction in progress
{"name":"pg-online-schema-change","hostname":"Bryces-MacBook-Pro-M2.local","pid":19905,"level":30,"time":"2023-07-27T17:34:51.937-04:00","v":0,"msg":"Running alter statement on shadow table","shadow_table":"pgosc_st_mytable_c16c36","parent_table":"mytable","version":"0.9.2"}
WARNING:  there is already a transaction in progress
{"name":"pg-online-schema-change","hostname":"Bryces-MacBook-Pro-M2.local","pid":19905,"level":30,"time":"2023-07-27T17:34:52.051-04:00","v":0,"msg":"Clearing contents of audit table before copy..","shadow_table":"pgosc_st_mytable_c16c36","parent_table":"mytable","version":"0.9.2"}
WARNING:  there is already a transaction in progress
{"name":"pg-online-schema-change","hostname":"Bryces-MacBook-Pro-M2.local","pid":19905,"level":30,"time":"2023-07-27T17:34:52.148-04:00","v":0,"msg":"Copying contents..","shadow_table":"pgosc_st_mytable_c16c36","parent_table":"mytable","version":"0.9.2"}
WARNING:  there is already a transaction in progress
WARNING:  there is already a transaction in progress
```

Is there a way to show any sort of progress indicator while the tool is running? I realize this would be challenging as the `copy_data!` command is just running a query inside a larger transaction. I'm not sure if it's even possible to get visibility into this, but it sure would be nice!

**Comment by jfrost** [comment]
You could take a look at `pg_stat_activity` with something like:

```
SELECT *
  FROM pg_stat_activity
 WHERE state <> 'idle'
;
```

and see what's happening on the db side.

**Comment by brycethornton** [comment]
@jfrost Yeah, I can see the `INSERT INTO` running in the process list. Just no idea how long it will take. My original command failed with an `PQconsumeInput() server closed the connection unexpectedly (PG::ConnectionBad)` error after over 20 hours. I have it running again to see if I can actually get it to run successfully. It brings to mind so many nice potential features:

- Showing progress
- Restarting a failed process (need to keep persisted state somehow)
- Some sort of preview/recommendation feature that scan the size of your database, looks at the host resources (CPU/Memory), and various PG settings (`max_wal_size` etc.), and gives an idea of how long the process might take and any tweaks that might help.

Anyway, we'll see how this turns out. I also have a custom SQL script running on a test instance that uses [a different approach for changing a primary key from int4 to int8](http://zemanta.github.io/2021/08/25/column-migration-from-int-to-bigint-in-postgresql/). Hopefully one of these will succeed and I can run it on the real thing and move on.

**Comment by brycethornton** [comment]
Quick update, I did finally get the command to finish on a test instance. It took a little over 21 hours. Some way to show progress would be nice, though. Feel free to close this issue if there's no viable way to do it.

**Comment by sasharevzin** [comment]
@brycethornton They have `--verbose` command to show you what is currently happening.

**Comment by brycethornton** [comment]
> They have `--verbose` command to show you what is currently happening.

@sasharevzin Thanks. Yeah, that does add some handy output but the specific area where I would love some more visibility is during the `Copying contents..` portion. I know what happens during this time but I don't know how far long it is at any given time. It's not a huge deal on smaller tables but on a really large table it would be really hand to know that it's 25%, 50%, 75%, etc. done with the "INSERT INTO..." statement. I don't think there's a good way to do this unfortunately.

**Comment by shayonj** [comment]
I wonder if we periodically compare the count of the rows between tables and log a percentage complete every minute or so. I guess it might be hard to do with the transaction that is running the copy not completed 🤔

**Comment by brycethornton** [comment]
Yeah, I haven't been able to find a way to do it since the shadow table creation and insertion are all within the same transaction. I can't get any visibility.

**Comment by jfrost** [comment]
Sorry I'm late writing back...vacation got a little hectic. The joys of MVCC keep us from really seeing what the row count is. The only thing I can think of would be to look at the on disk file sizes, but you can only do that if you have access to the filesystem, so no way to do it on platforms like RDS.

**Comment by brycethornton** [comment]
My workaround on RDS was to monitor the free storage space. Since this was such a big table I could roughly see how far along it was as free storage space shrunk:

<img width="223" alt="image" src="https://github.com/shayonj/pg-osc/assets/4918/99308890-c092-48e4-bb61-9d572b3ac3e9">

**Comment by jfrost** [comment]
Oh good point and you could watch the raw metric in cloudwatch if it's a smaller table. That would work well enough for DBs with relatively stable sizes and big tables like you mentioned!

**Comment by ngan** [comment]
@shayonj is it possible to do this on the shadow table and compare it to the original table? That'll give you a decent sense of progress. I have no idea whether this works on the shadow table while it's in a transaction.

```
SELECT pg_size_pretty(pg_total_relation_size('"<schema>"."<table>"'));
```

**Comment by shayonj** [comment]
ah! i missed that the table creation happens from the same transaction as well, which means the table isn't visible to another connection either. 

This is interesting....

https://github.com/shayonj/pg-osc/blob/baa638f5a48fbc0289b74d3ce2c76602a9b7482a/lib/pg_online_schema_change/orchestrate.rb#L166-L175

**Comment by shayonj** [comment]
v0.9.7 is now out with the new estimated progress in logs during copy: https://github.com/shayonj/pg-osc/releases/tag/v0.9.7

Please feel free to share any ideas, feedback and bugs. Thanks everyone for all the brainstorming and feedback. 

Closing now.

**Comment by brycethornton** [comment]
Thank you, @shayonj! I'm excited to give this a spin soon!

**Comment by shayonj** [comment]
Woot! Would love to hear your thoughts. 

Going to release 0.9.8 today evening. Looks like there are some gem version conflicts currently. Stay tuned.
