### ISSUE TITLE
INSERT's are failing for long table names

### ISSUE THREAD

**Issue by ahilmer** [shayonj/pg-osc#115]
Hi pg-osc team,

we successfully used your tool to rebuild a bloated table on production without any downtime! It shrank from around 400GB down to 100GB.

During the testing phase we had to apply some custom adoptions to the source code which we would like to contribute back :smiley: 

This one handles a bug where an INSERT into the primary table fails during the execution on a large table name ( e.g. `this_is_a_table_with_a_very_long_name`).

#### Steps to reproduce

1. Minimal test setup
```
drop table if exists "this_is_a_table_with_a_very_long_name";

 CREATE TABLE IF NOT EXISTS "this_is_a_table_with_a_very_long_name" (
id int PRIMARY KEY,
"createdOn" TIMESTAMP NOT NULL
);
      
insert into "this_is_a_table_with_a_very_long_name"("id", "createdOn") values(1, '2012-01-01')
```

2. Add a breakpoint

![Selection_885](https://github.com/shayonj/pg-osc/assets/4171011/fceb52fd-a9af-4dd0-819b-620fbed50838)

3. run pg-osc

```
bundle exec bin/pg-online-schema-change perform  --host localhost --dbname postgres --username celonis  --alter-statement 'alter table this_is_a_table_with_a_very_long_name alter column id TYPE int'
```

4. Run an INSERT

![Selection_884](https://github.com/shayonj/pg-osc/assets/4171011/334aa358-448a-4332-8586-9c24e46ae3ce)

==> Result: The INSERT into the primary table fails

#### Suggested Solution
Read the real sequence name using `SELECT pg_get_serial_sequence(:table, :column`)

**Comment by ahilmer** [comment]
I forked the repository and adding here the PR https://github.com/shayonj/pg-osc/pull/116

Happy to hear back from you :smiley:

**Comment by shayonj** [comment]
Closed via https://github.com/shayonj/pg-osc/pull/116
