### ISSUE TITLE
Scope of this tool

### ISSUE THREAD

**Issue by sunilgandipadala** [shayonj/pg-osc#122]
Hi, 

Is this pg-osc, only available for ALTER TABLE statements or does it work for any ALTER statements, like ALTER INDEX and some more..?

As when I tried to run the following alter statement with pg-osc , got an error metioned below.

pg-online-schema-change perform --alter-statement 'ALTER INDEX IF EXISTS unq_trace_id RENAME TO modified_name;'  --dbname "testdb" --host "localhost" --username "postgres" --wait-time-for-lock 5 --kill-backends --drop

**Error:**
/var/lib/gems/3.0.0/gems/pg_online_schema_change-0.9.4/lib/pg_online_schema_change/orchestrate.rb:56:in `run!': Parent table has no primary key, exiting... (PgOnlineSchemaChange::Error)

**Comment by shayonj** [comment]
Hi! Yes, a primary key needs to be present on the table for the alter operations, since the tool is primarily solving issues w/ schema changes. 

See: https://github.com/shayonj/pg-osc#caveats

Closing, but feel free to re-open with any questions or if I missed anything.
