### ISSUE TITLE
fails to get view definition if it is from another schema

### ISSUE THREAD

**Issue by Shohou** [shayonj/pg-osc#129]
This is probably related to #112 and #117. When script tries to get view definition it fails because view is not from public schema
![image](https://github.com/shayonj/pg-osc/assets/1607593/722ecb6a-2c12-4256-9a9e-00732c182d3d)
As you can see it tries to select pg_get_viewdef(format('%I.%I', '**public**', dependent_view.relname)::regclass) as view_definition and not all of my views are from public schema. Probably should be something like

SELECT DISTINCT dependent_view.relname as view_name, pg_get_viewdef(format('%I.%I', **view_ns.nspname**, dependent_view.relname)::regclass) as view_definition
FROM pg_depend
JOIN pg_rewrite ON pg_depend.objid = pg_rewrite.oid
JOIN pg_class as dependent_view ON pg_rewrite.ev_class = dependent_view.oid
JOIN pg_class as source_table ON pg_depend.refobjid = source_table.oid
JOIN pg_namespace source_ns ON source_ns.oid = source_table.relnamespace
**JOIN pg_namespace view_ns ON view_ns.oid = dependent_view.relnamespace**
where
source_ns.nspname = 'public'
AND source_table.relname = 'pgosc_op_table_users';

**Comment by Shohou** [comment]
version used 0.9.5

**Comment by shayonj** [comment]
oh interesting! So does that mean you have table in one schema and multiple views referencing the table in different schema? 

In other words, so the `schema` that you provide to pg-osc cli is not necessary tied to all the view?

**Comment by Shohou** [comment]
exactly! :)

**Comment by shayonj** [comment]
Thanks again! Released in https://github.com/shayonj/pg-osc/releases/tag/v0.9.6
