### ISSUE TITLE
Does pg-osc is able to insert millions of rows to an existing table? 

### ISSUE THREAD

**Issue by sunil904** [shayonj/pg-osc#135]
I have a CSV file with millions of rows which I need to add them into a table. Either by **truncate and load** or directly **load** . 

Can I do it using pg-osc? If yes, how can I?

**Comment by shayonj** [comment]
pg-osc doesn't support that feature. The description of tools capabilities are in the readme: https://github.com/shayonj/pg-osc

Please feel free to re-open the issue with any feature requests, bugs or questions. Thanks!

**Comment by shayonj** [comment]
Note : pg osc can replicate any tables of any size but not load data into a non existing table from a source like cav
