### ISSUE TITLE
How does this will work in a live project.

### ISSUE THREAD

**Issue by sunilgandipadala** [shayonj/pg-osc#149]
Hi, 

I have my live project, that I want to use pg-osc to alter my tables where those tables have billions of rows of data. Now, how can I do it. 

I have only idea of every time calling the pg-osc command with alter statements **manually**.  

Other than, this is there any way to do the same task?

**Comment by shayonj** [comment]
Hi! I am not sure i am following what you are looking for. Have you already trying using `pg-osc`/`pg_online_schema_change`? If so, can you share what you have tried or whats not working.

**Comment by shayonj** [comment]
Oh I see! Yes you very much can! Thanks for checking

**Comment by shayonj** [comment]
Closing the issue but feel free to reopen if you encounter any bugs or have feature requests
