### ISSUE TITLE
Update Readme reg- docker setup of pg-osc

### ISSUE THREAD

**Issue by sunilgandipadala** [shayonj/pg-osc#153]
Hey, 

please update readme regarding the installation of pg-osc through docker and give steps to use it using docker.

![image](https://github.com/shayonj/pg-osc/assets/65104532/8ca21aef-6201-4428-bb44-3492f5fc6535)
Also, explain the fields and could you please provide the values of the fields.

**Comment by shayonj** [comment]
There description [here](https://hub.docker.com/r/shayonj/pg-osc) links to the Github Readme which has some examples. Do you think thats good? If not, PRs welcome with more examples in the Readme 🙌🏾

**Comment by shayonj** [comment]
Closing the issue, but open to PRs or any other suggestions. Thanks!
