### ISSUE TITLE
Error case with delta-count and pull-batch-count values

### ISSUE THREAD

**Issue by tanelsuurhans** [shayonj/pg-osc#165]
I stumbled upon a scenario where setting the `delta-count` argument value to be equal or larger than the `pull-batch-count` value results in the replay phase running one cycle, thinking the remaining row count is smaller (or equal) to the `delta_count` value and performs the swap right away, even though there are plenty of rows left in the replay table.

Opened a [pull request](https://github.com/shayonj/pg-osc/pull/164) to address this by introducing a validation to enforce the `delta-count` value to always be smaller than the `pull-batch-count` value.

**Comment by shayonj** [comment]
Thanks for the issue & PR. Also, very happy to see the project being used at ID.me (judging by the branch name :D). Feel free to drop any feature requests / bugs you come across 🙏🏽
