### ISSUE TITLE
Re-enable autovacuum and fix sequence naming post swap

### ISSUE THREAD

**Issue by shiwangini93** [shayonj/pg-osc#69]
pgosc disables autovacuum for the new table it creates  - (probably because we want to go with faster inserts ),so we need to re-enable autovacuum manually for the new fresh table.

Also, it gives some weird name to sequence and primary key which we also need to rename back/correct. In my case , there was a dependent function on that table sequence ,so that stopped working :)

**Comment by shayonj** [comment]
Hi @shiwangini93 - We actually, do we restore storage params (autovaccum) and any other settings on a table here: 
https://github.com/shayonj/pg-osc/blob/f47f7aac481b5202c17899b2f8ace7cc6bbe8cf5/lib/pg_online_schema_change/orchestrate.rb#L246

Could you share an example perhaps? Also note that, pg-osc isn't compatible with partitioned tables yet (https://github.com/shayonj/pg-osc/issues/68), so in case this is related to https://github.com/shayonj/pg-osc/issues/68, its normal in this case to not see the vaccum settings transferred. 

Regarding the sequence naming, collapsing that into: https://github.com/shayonj/pg-osc/issues/20

Closing the issue for now, but please feel free to re-open in case you see any issues with autovaccum settings being not restored. Thanks
