### ISSUE TITLE
Feature Request: We want to make it working with the table with trigger 

### ISSUE THREAD

**Issue by shiwangini93** [shayonj/pg-osc#70]
We want to make it working with the table with trigger  :)

**Comment by shayonj** [comment]
Hi @shiwangini93, thank you for the feature request. Could you share a bit more context on the feature and what kind of table/trigger functionality you have in mind?

**Comment by shiwangini93** [comment]
@shayonj  - I tried to add a column on a table which had an `on insert` trigger. But, when i executed my ddl with pgosc,it created new table with the added column. But, the new table didn't have the `on insert` trigger which my real table had. Hope you got it or let me know if you need example for it

**Comment by shayonj** [comment]
ah! i see. Let me look into this in the next two weekends. Keep you posted! Thanks for the report @shiwangini93

**Comment by ananichev** [comment]
@shayonj Hello
Is there any update on triggers? I faced the same issue as @shiwangini93

**Comment by shayonj** [comment]
ah! sorry you are running into this too @ananichev . I am going to look into this in the next few days and get back to you.

**Comment by shayonj** [comment]
Fixed and out in the latest release: https://github.com/shayonj/pg-osc/releases/tag/v0.7.5

Thanks for the report and the patience @ananichev @shiwangini93. Feel free to open more feature reqs or bugs you run into.

**Comment by ananichev** [comment]
Thanks!
