### ISSUE TITLE
Set the appropriate next sequence value on the new table

### ISSUE THREAD

**Issue by brycethornton** [shayonj/pg-osc#71]
First, thank you for creating this project. It's great to have something that can automate table re-writing with all the best practices to avoid downtime.

When I used this a few months back everything worked great besides the primary key's sequence value. The value was left at 1 which meant I immediately starting seeing duplicate key issues. When I figured out what was happening all I needed to do was manually set the value of the sequence to the max id + 1 of the primary key and things started working again.

1. Is this a known issue? I've seen other issues around sequence naming but I haven't seen others mention the actual sequence value. I feel like I'm missing something.

2. Would there be any potential issues with executing something like this pseudocode  at the end of the `swap!` method? 

`SELECT SETVAL('#{client.pk_sequence}', (SELECT MAX(#{client.pk}) FROM #{client.table})+1);`

Another idea I had was to simply allow a configurable `--post-swap-statement` option that would run custom SQL to do whatever lingering cleanup was needed for the user's specific case.

**Comment by shayonj** [comment]
This is a bug! Thanks for opening a report @brycethornton . I should have a fix/PR today (tomorrow latest). And, yep the pseudocode is likely what we can do here.

**Comment by shayonj** [comment]
thanks again @brycethornton . Let me know in case you run into any others issues and/or have feature requests. I like the idea of `--post-swap-statement`, perhaps we can track it in a separate ticket.

**Comment by brycethornton** [comment]
Thanks for the quick response, @shayonj! I'll give this a try shortly and will use it on a big production project early next week if all goes well.

**Comment by shayonj** [comment]
exciting !!

**Comment by brycethornton** [comment]
@shayonj are you planning to bump the version and cut a new release?

**Comment by shayonj** [comment]
yep - all released now

https://github.com/shayonj/pg-osc/releases/tag/v0.7.2

**Comment by brycethornton** [comment]
I'm not sure this change is actually in the 0.72 release. I tried the release this morning and wasn't seeing the intended behavior and then I looked at the diff between 0.71 and 0.72 and didn't see it there either.

https://github.com/shayonj/pg-osc/compare/v0.7.1...v0.7.2

**Comment by brycethornton** [comment]
No worries. I just patched my local gem with your change and it worked flawlessly today on a large production table.

**Comment by shayonj** [comment]
Thats great to hear! thanks @brycethornton . I have changes ready mostly, will get a new version out this weekend.

**Comment by shayonj** [comment]
0.7.3 is now out @brycethornton . Thanks again for your patience!!
