### ISSUE TITLE
Potential need for a `pull-batch-delay` option

### ISSUE THREAD

**Issue by brycethornton** [shayonj/pg-osc#80]
I ran into an issue recently while testing this library on a rather large (250GB) table on Heroku. I've used this tool in a few other cases but this is the largest table I've tried yet. Here's the message I got from Heroku while running the alter statement:

```
Your database is currently unable to keep up with writes.

Specifically, Postgres is unable to archive Postgres write-ahead logs (WAL) fast enough to keep up with write volume. WAL archiving is critical to maintaining continuous protection of data.

If the WAL drive fills completely, the database will shut down and will be at risk of data loss. To prevent this, Heroku is temporarily throttling your database connections to allow the backlog of WAL to be archived.

Heroku strongly recommends pausing or reducing any bulk data loading activity that is running.

Heroku will remove the connection throttling once WAL archiving is able to keep up with database writes.

Read more about this here: https://devcenter.heroku.com/articles/postgres-write-ahead-log-usage
```

So, it was writing too fast and eventually the connection was killed. My assumption is that it might be able to succeed if I slow down the batches a bit by adding an optional delay/sleep argument for each batch. I don't really want the job to take even longer but it might be the only way in this situation. What are your thoughts on adding this? I'm happy to do the work, I just wanted to check to see if there were other potential options for this case before I opened a PR.

Thanks.

**Comment by shayonj** [comment]
oh interesting! Yeah, I'd be down for that, but I wonder if a shorter `pull-batch-count` would work here? say 100 rows at a time? Or would that be quite slow?



I reckon the [delete from](https://github.com/shayonj/pg-osc/blob/54c242e0f76f77347281e30a47d76e3878cbc29c/lib/pg_online_schema_change/replay.rb#L120) is only adding to the additional WAL volume. I will try to see if there are some alternative design approaches we can perform to reduce the WAL level usage soon. In the meantime, I am open to `pull-batch-delay` also.

**Comment by brycethornton** [comment]
Closing this as compressing WAL files helped get this done without the need for arbitrary sleeps.

**Comment by shayonj** [comment]
wonderful! thanks for sharing @brycethornton
